Repository untukkita-id/sda.untukkita.id, pull requests merged in 2021-08, with the labels that each got.

#13 feat: submenu faskes
  .eslintignore
  .github/workflows/lighthouse-pr.yml
  CODE_OF_CONDUCT.md
  components/navbar-faskes.js
  pages/fasilitas-kesehatan/apotek.js
  pages/fasilitas-kesehatan/index.js
  pages/fasilitas-kesehatan/oksigen.js
  pages/fasilitas-kesehatan/puskesmas.js
Labels: enhancement

#22 14-feat-ssg-rendering
  .eslintignore
  .eslintrc.js
  .github/workflows/lighthouse-pr.yml
  .github/workflows/test.yml
  .gitignore
  components/home/home-menu.js
  jsconfig.json
  lib/faskes-splitter.js
  next.config.js
  package.json
  pages/api/data/faskes/[faskes].js
  pages/api/data/faskes/index.js
  pages/fasilitas-kesehatan.js
  pages/fasilitas-kesehatan/apotek.js
  pages/fasilitas-kesehatan/index.js
  pages/fasilitas-kesehatan/oksigen.js
  pages/fasilitas-kesehatan/puskesmas.js
  yarn.lock
Labels: type-improvement, type-refactor, priority-high, status-merge, scope-security, scope-performance

#30 chore: Absolute import components
  .eslintrc.js
  .github/ISSUE_TEMPLATE/epics.md
  .github/workflows/linter.yml
  components/header.js
  components/layout/markdownpages.js
  jsconfig.json
  lib/faskes-fetcher.js
  lighthouserc-pr.js
  package.json
  pages/404.js
  pages/500.js
  pages/fasilitas-kesehatan/apotek.js
  pages/fasilitas-kesehatan/index.js
  pages/fasilitas-kesehatan/oksigen.js
  pages/fasilitas-kesehatan/puskesmas.js
  pages/index.js
  pages/kebijakan-data.mdx
  pages/kontak-darurat.js
  pages/kontak-kami.mdx
  pages/tentang-kami.mdx
  yarn.lock
Labels: type-improvement, type-refactor, scope-dx
